### ISSUE TITLE
RedM/Peds: "Request Control" cannot be selected

### ISSUE THREAD

**Issue by DintyGadget** [kibook/spooner#11]
![image](https://user-images.githubusercontent.com/25077548/128717133-4ffd6f05-da50-48b0-9a26-32e1d0625d3b.png)
Perhaps I do not quite understand how this function works, but I am unable to activate it. I turned on all rights available to everyone, and even that didn’t work.

**Comment by DintyGadget** [comment]
So this feature does not allow you to control Ped in real time?

**Comment by kibook** [comment]
No, it does not.

Entities in GTA V and RDR 2 are "controlled" by one specific player at any given time. Only this player can manipulate them. Normal interactions with an entity like getting on a mount, entering the driver's seat of a vehicle, or shooting a ped will automatically request control of the entity so that you can perform that interaction.

There are times when the game may not give you control for some reason, so this button acts as an indicator of whether or not you have control in order to determine if that's the reason you can't move/rotate/change properties of the entity in spooner. An example is when a player has left the game without quitting properly. Entities they had control of will be stuck in their control until they timeout.
