### ISSUE TITLE
I can only spawn CERTAIN entitys

### ISSUE THREAD

**Issue by finlayrough** [kibook/spooner#24]
I can only spawn like one entity from the objects menu

I've set it up right (I think)
I've even changed the keybinds, but still I can only spawn certain objects.

**Comment by kibook** [comment]
Which object can you spawn? What is an example of one you cannot spawn? Is this on FiveM or RedM?

**Comment by finlayrough** [comment]
It's on FiveM, and I think I have figured out the problem. Lots of the entities in the 'objects' category have commas at the end of their names. Because of this, they cannot be spawned. The ones without commas at the end are the only ones that can be spawned.

**Comment by finlayrough** [comment]
Is this going to be fixed?

**Comment by kibook** [comment]
Check the link above.

**Comment by finlayrough** [comment]
Right thanks.

**Comment by TayMcKenzieNZ** [comment]
Apologies, I'd made a typo in my pull request. Some props simply won't spawn because they require the new gamebuild that isn't supported by FiveM just yet. I've added them beforehand so that all server owners would need to do is enforce the gamebuild to the newest build and all props new and old, would work. 

However had made a typo in the code which is why you faced your initial bug; Kibook has since fixed this 😊
