### ISSUE TITLE
my friend cant see things which i have added 

### ISSUE THREAD

**Issue by darkserene** [kibook/spooner#30]
so i followed the steps and first of all id like to say what an amazing script you have created but sadly my friend can only see some of the objects i put in he sees all peds and all animals but is not able to see some objects is this a issue i can sort or can you help thanks i have saved a database and when i click it in the spooner menu everything works for me

**Comment by kibook** [comment]
The games limit the number of objects that can be networked at one time. In RDR 2 this seems to be around 60 objects. I'm not sure about GTA V. This means that at a certain point, objects you spawn will not be visible to other players until some other networked objects are removed.

You can tell if this is happening by looking at the ID number of objects when hovering over them or in the database or properties menus. All objects have a local ID (like `12345`), but networked objects will also have a secondary network ID in square brackets (like `[42]`). If you spawn an object and it does not receive a network ID, only a local ID, then the object will not be visible to other players because it is not networked. It should automatically become networked as soon as there is space, when other nearby networked objects are deleted.

For large custom maps with lots of objects, you'll probably want to look into exporting these to either the ymap format and streaming them as a resource (assuming this is your server), or the Map Editor XML format and loading it with another script of mine, [objectloader](https://github.com/kibook/redm-objectloader). Both of these spawn the objects non-networked for all players separately, avoiding the limitations on networked objects. ymap is generally better as it is the native map format for GTA V and RDR 2, and has no issues with even thousands of objects, but if you have objects inside interiors, you'd have to use objectloader, as a ymap won't correctly spawn objects inside an interior (that would be handled by a native ytyp file). objectloader is limited to around 300-400 objects, however, as the game will have issues if you spawn more than that via script as it does.
